# Generated by Django 4.0 on 2024-02-24 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StdDetailes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdname', models.CharField(max_length=100)),
                ('stdcourse', models.CharField(max_length=100)),
                ('stdbranch', models.CharField(max_length=100)),
                ('stdjoining', models.DateTimeField()),
                ('stdvillage', models.CharField(max_length=100)),
                ('stdmcetrank', models.IntegerField()),
                ('stdphoto', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
