# Generated by Django 4.0 on 2024-02-24 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stddetailes',
            name='stdjoining',
            field=models.DateField(),
        ),
    ]
