# Generated by Django 4.0 on 2024-02-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_alter_stddetailes_stdjoining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stddetailes',
            name='stdjoining',
            field=models.DateTimeField(),
        ),
    ]
