# Generated by Django 4.0 on 2024-02-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_alter_stddetailes_stdjoining'),
    ]

    operations = [
        migrations.AddField(
            model_name='stddetailes',
            name='stdemail',
            field=models.EmailField(default='g', max_length=254),
            preserve_default=False,
        ),
    ]
